// Exports contract ABIs from Foundry build output into typed TS modules for the app and scripts.
// Usage: (cd contracts && forge build) && node scripts/src/export-abis.mjs
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const contracts = [
  "GiftVault",
  "GiftCardNFT",
  "ScheduledGifts",
  "GroupPot",
  "FeeCollector",
  "ProjectTokenHooks",
  "OracleAdapter",
  "TrustedForwarder",
  "ComplianceRegistry",
  "Timelock",
];

let out = "// AUTO-GENERATED by scripts/src/export-abis.mjs from contracts/out. Do not edit.\n\n";
for (const name of contracts) {
  const artifact = JSON.parse(readFileSync(join(root, "contracts", "out", `${name}.sol`, `${name}.json`), "utf8"));
  out += `export const ${name[0].toLowerCase()}${name.slice(1)}Abi = ${JSON.stringify(artifact.abi)} as const;\n\n`;
}

for (const target of [join(root, "app", "src", "config", "generated", "abis.ts"), join(root, "scripts", "src", "generated", "abis.ts")]) {
  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, out);
  console.log("wrote", target);
}
